"""
agents/report_agent.py
-----------------------
Agent 4 – Report Agent
Assembles all previous agent outputs into a professional PDF report.
"""
import os
import re
from datetime import datetime
from fpdf import FPDF
from config.settings import REPORTS_DIR


def _safe(text: str) -> str:
    """Replace common Unicode characters with ASCII equivalents, then drop anything outside latin-1."""
    replacements = {
        "\u2013": "-",   # en-dash
        "\u2014": "--",  # em-dash
        "\u2018": "'",   # left single quote
        "\u2019": "'",   # right single quote
        "\u201c": '"',   # left double quote
        "\u201d": '"',   # right double quote
        "\u2022": "*",   # bullet
        "\u2026": "...", # ellipsis
        "\u00a0": " ",   # non-breaking space
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    # Drop anything still outside latin-1
    return text.encode("latin-1", errors="ignore").decode("latin-1")


class ReportAgent:
    def run(self, filename, extraction_result, research_result, summary_result):
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        base = os.path.splitext(filename)[0]
        report_filename = f"{base}_report_{timestamp}.pdf"
        report_path = os.path.join(REPORTS_DIR, report_filename)

        pdf = _ReportPDF()
        pdf.alias_nb_pages()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        # Cover info
        pdf.set_font("Helvetica", "B", 22)
        pdf.set_text_color(30, 60, 120)
        pdf.cell(0, 14, "Enterprise Intelligence Report", ln=True, align="C")
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(80, 80, 80)
        pdf.cell(0, 8, f"Source file: {_safe(filename)}", ln=True, align="C")
        pdf.cell(0, 8, f"Generated: {datetime.now().strftime('%d %B %Y  %H:%M')}", ln=True, align="C")
        pdf.ln(6)
        pdf.set_draw_color(30, 60, 120)
        pdf.set_line_width(0.8)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(6)

        # Document stats
        pdf.section_title("Document Statistics")
        stats = [
            ("File name",            extraction_result.get("filename", filename)),
            ("Source type",          extraction_result.get("source_type", "-")),
            ("Characters extracted", f"{extraction_result.get('char_count', 0):,}"),
            ("Words extracted",      f"{extraction_result.get('word_count', 0):,}"),
        ]
        for label, value in stats:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(50, 50, 50)
            pdf.cell(55, 7, f"{_safe(label)}:", ln=False)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(0, 7, _safe(str(value)), ln=True)
        pdf.ln(4)

        # Summary
        if summary_result.get("success"):
            pdf.section_title("Summary & Insights")
            pdf.body_text(summary_result.get("summary", ""))
            pdf.ln(4)

        # Research
        if research_result.get("success"):
            pdf.section_title("Research Analysis")
            pdf.body_text(research_result.get("analysis", ""))
            pdf.ln(4)

        # Raw text excerpt
        raw_text = extraction_result.get("text", "")
        if raw_text:
            pdf.section_title("Document Text Excerpt (first 1,000 words)")
            excerpt = " ".join(raw_text.split()[:1000])
            pdf.body_text(excerpt)

        pdf.output(report_path)
        return {"success": True, "report_path": report_path, "filename": report_filename}


class _ReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, "Multi-Agent Enterprise Intelligence System", ln=False, align="L")
        self.cell(0, 8, f"Page {self.page_no()}/{{nb}}", ln=True, align="R")
        self.ln(2)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(180, 180, 180)
        # Use plain ASCII hyphen - not an en-dash
        self.cell(0, 8, "Confidential - Generated by MAEIS", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(30, 60, 120)
        self.cell(0, 9, _safe(title), ln=True)
        self.set_draw_color(200, 210, 230)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)
        self.set_text_color(0, 0, 0)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(30, 30, 30)
        self.multi_cell(0, 6, _safe(text))